server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-base #注册中心 中的名字
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.115.131:3306/project_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
